// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DespatchBay.shipping.api.despatchbaypro.com {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ShippingServiceBinding", Namespace="urn:despatchbay")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ServiceType))]
    public partial class ShippingService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetDomesticServicesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDomesticServicesByPostcodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetShipmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddDomesticShipmentOperationCompleted;
        
        /// CodeRemarks
        public ShippingService() {
            this.Url = "http://api.despatchbaypro.com/soap/v11/shipping.php";
        }
        
        public ShippingService(string url) {
            this.Url = url;
        }
        
        /// CodeRemarks
        public event GetDomesticServicesCompletedEventHandler GetDomesticServicesCompleted;
        
        /// CodeRemarks
        public event GetDomesticServicesByPostcodeCompletedEventHandler GetDomesticServicesByPostcodeCompleted;
        
        /// CodeRemarks
        public event GetShipmentCompletedEventHandler GetShipmentCompleted;
        
        /// CodeRemarks
        public event AddDomesticShipmentCompletedEventHandler AddDomesticShipmentCompleted;
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:despatchbay#GetDomesticServices", RequestNamespace="urn:despatchbay", ResponseNamespace="urn:despatchbay")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public ServiceType[] GetDomesticServices(string postcode) {
            object[] results = this.Invoke("GetDomesticServices", new object[] {
                        postcode});
            return ((ServiceType[])(results[0]));
        }
        
        /// CodeRemarks
        public void GetDomesticServicesAsync(string postcode) {
            this.GetDomesticServicesAsync(postcode, null);
        }
        
        /// CodeRemarks
        public void GetDomesticServicesAsync(string postcode, object userState) {
            if ((this.GetDomesticServicesOperationCompleted == null)) {
                this.GetDomesticServicesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDomesticServicesOperationCompleted);
            }
            this.InvokeAsync("GetDomesticServices", new object[] {
                        postcode}, this.GetDomesticServicesOperationCompleted, userState);
        }
        
        private void OnGetDomesticServicesOperationCompleted(object arg) {
            if ((this.GetDomesticServicesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDomesticServicesCompleted(this, new GetDomesticServicesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:despatchbay#GetDomesticServicesByPostcode", RequestNamespace="urn:despatchbay", ResponseNamespace="urn:despatchbay")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public ServiceType[] GetDomesticServicesByPostcode(string postcode) {
            object[] results = this.Invoke("GetDomesticServicesByPostcode", new object[] {
                        postcode});
            return ((ServiceType[])(results[0]));
        }
        
        /// CodeRemarks
        public void GetDomesticServicesByPostcodeAsync(string postcode) {
            this.GetDomesticServicesByPostcodeAsync(postcode, null);
        }
        
        /// CodeRemarks
        public void GetDomesticServicesByPostcodeAsync(string postcode, object userState) {
            if ((this.GetDomesticServicesByPostcodeOperationCompleted == null)) {
                this.GetDomesticServicesByPostcodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDomesticServicesByPostcodeOperationCompleted);
            }
            this.InvokeAsync("GetDomesticServicesByPostcode", new object[] {
                        postcode}, this.GetDomesticServicesByPostcodeOperationCompleted, userState);
        }
        
        private void OnGetDomesticServicesByPostcodeOperationCompleted(object arg) {
            if ((this.GetDomesticServicesByPostcodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDomesticServicesByPostcodeCompleted(this, new GetDomesticServicesByPostcodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:despatchbay#GetShipment", RequestNamespace="urn:despatchbay", ResponseNamespace="urn:despatchbay")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public ShipmentReturnType GetShipment(string ShipmentID) {
            object[] results = this.Invoke("GetShipment", new object[] {
                        ShipmentID});
            return ((ShipmentReturnType)(results[0]));
        }
        
        /// CodeRemarks
        public void GetShipmentAsync(string ShipmentID) {
            this.GetShipmentAsync(ShipmentID, null);
        }
        
        /// CodeRemarks
        public void GetShipmentAsync(string ShipmentID, object userState) {
            if ((this.GetShipmentOperationCompleted == null)) {
                this.GetShipmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetShipmentOperationCompleted);
            }
            this.InvokeAsync("GetShipment", new object[] {
                        ShipmentID}, this.GetShipmentOperationCompleted, userState);
        }
        
        private void OnGetShipmentOperationCompleted(object arg) {
            if ((this.GetShipmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetShipmentCompleted(this, new GetShipmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:despatchbay#AddDomesticShipment", RequestNamespace="urn:despatchbay", ResponseNamespace="urn:despatchbay")]
        [return: System.Xml.Serialization.SoapElementAttribute("ShipmentID")]
        public string AddDomesticShipment(ShipmentRequestType Shipment) {
            object[] results = this.Invoke("AddDomesticShipment", new object[] {
                        Shipment});
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void AddDomesticShipmentAsync(ShipmentRequestType Shipment) {
            this.AddDomesticShipmentAsync(Shipment, null);
        }
        
        /// CodeRemarks
        public void AddDomesticShipmentAsync(ShipmentRequestType Shipment, object userState) {
            if ((this.AddDomesticShipmentOperationCompleted == null)) {
                this.AddDomesticShipmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddDomesticShipmentOperationCompleted);
            }
            this.InvokeAsync("AddDomesticShipment", new object[] {
                        Shipment}, this.AddDomesticShipmentOperationCompleted, userState);
        }
        
        private void OnAddDomesticShipmentOperationCompleted(object arg) {
            if ((this.AddDomesticShipmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddDomesticShipmentCompleted(this, new AddDomesticShipmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:despatchbay")]
    public partial class ServiceType {
        
        /// <remarks/>
        public int ServiceID;
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public float Cost;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:despatchbay")]
    public partial class ShipmentRequestType {
        
        /// <remarks/>
        public int ServiceID;
        
        /// <remarks/>
        public int ParcelQuantity;
        
        /// <remarks/>
        public string OrderReference;
        
        /// <remarks/>
        public string Contents;
        
        /// <remarks/>
        public string CompanyName;
        
        /// <remarks/>
        public string RecipientName;
        
        /// <remarks/>
        public string Street;
        
        /// <remarks/>
        public string Locality;
        
        /// <remarks/>
        public string Town;
        
        /// <remarks/>
        public string County;
        
        /// <remarks/>
        public string Postcode;
        
        /// <remarks/>
        public string RecipientEmail;
        
        /// <remarks/>
        public int EmailNotification;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool EmailNotificationSpecified;
        
        /// <remarks/>
        public int DashboardNotification;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool DashboardNotificationSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:despatchbay")]
    public partial class ShipmentReturnType {
        
        /// <remarks/>
        public string ShipmentID;
        
        /// <remarks/>
        public int ServiceID;
        
        /// <remarks/>
        public string CreateDate;
        
        /// <remarks/>
        public int ParcelQuantity;
        
        /// <remarks/>
        public string Printed;
        
        /// <remarks/>
        public string StartTrackingNumber;
        
        /// <remarks/>
        public string EndTrackingNumber;
        
        /// <remarks/>
        public string Despatched;
        
        /// <remarks/>
        public string DespatchDate;
        
        /// <remarks/>
        public string OrderReference;
        
        /// <remarks/>
        public string Contents;
        
        /// <remarks/>
        public string CompanyName;
        
        /// <remarks/>
        public string RecipientName;
        
        /// <remarks/>
        public string Street;
        
        /// <remarks/>
        public string Locality;
        
        /// <remarks/>
        public string Town;
        
        /// <remarks/>
        public string County;
        
        /// <remarks/>
        public string Country;
        
        /// <remarks/>
        public string Postcode;
        
        /// <remarks/>
        public string RecipientEmail;
        
        /// <remarks/>
        public int EmailNotification;
        
        /// <remarks/>
        public int DashboardNotification;
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void GetDomesticServicesCompletedEventHandler(object sender, GetDomesticServicesCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDomesticServicesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDomesticServicesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public ServiceType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceType[])(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void GetDomesticServicesByPostcodeCompletedEventHandler(object sender, GetDomesticServicesByPostcodeCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDomesticServicesByPostcodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDomesticServicesByPostcodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public ServiceType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceType[])(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void GetShipmentCompletedEventHandler(object sender, GetShipmentCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetShipmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetShipmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public ShipmentReturnType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ShipmentReturnType)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void AddDomesticShipmentCompletedEventHandler(object sender, AddDomesticShipmentCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddDomesticShipmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddDomesticShipmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
